In [1]:
import numpy as np

In [2]:
note_resolution = 12
intervals = [0, 2, 2, 1, 2, 2, 2]
max_len = len(intervals)
min_len = 2

In [3]:
# build sequence given intervals
scale = np.zeros((len(intervals), note_resolution))
scale[np.arange(len(intervals)), np.cumsum(intervals) % note_resolution] = 1

In [4]:
# shift to obtain different modes
seqs = [np.roll(scale, -i, axis=0) for i in xrange(len(scale))]

In [5]:
# shift to obtain different tonics
for i in xrange(len(seqs)):
    for j in xrange(1, note_resolution):
        sequence = np.roll(seqs[i], -j, axis=1)
        seqs.append(sequence)

In [6]:
# add reverse of all
for i in xrange(len(seqs)):
    seqs.append(seqs[i][::-1])

In [7]:
masks = []
# create all possible masks per sequence of length [min_len, max_len]
for i in xrange(min_len, max_len):
    mask = np.zeros((len(intervals), ), dtype=np.int32)
    mask[:i] = 1
    masks.append(mask)
    # not necessary to shift masks because sequences are shifted
    # for j in xrange(0, 1+max_len - i):
    #    masks.append(np.roll(mask, j))

In [13]:
masks[-1]

array([1, 1, 1, 1, 1, 1, 0], dtype=int32)

In [8]:
input_data, target_data, mask_data = [], [], []

In [9]:
for mask in masks:
    for seq in seqs:
        input_data.append(seq)
        target_data.append(seq[np.count_nonzero(mask)])
        mask_data.append(mask)

In [10]:
input_data = np.array(input_data)
target_data = np.array(target_data)
mask_data = np.array(mask_data)

In [11]:
i = 0
print input_data[i]
print target_data[i]
print mask_data[i]

[[ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.]]
[ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.]
[1 1 0 0 0 0 0]
